version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/monzo-python

    steps:
      - checkout
      - run:
          name: Lint
          command: |
            pip install black
            black --check --diff --target-version py38 monzo/ tests
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            python -m pytest tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports
